#!/bin/bash

set -eu

if [ -f configV ]
then
    source configV
fi

TMPFILE=`mktemp`
trap "/bin/rm -f $TMPFILE" ERR EXIT

found_ddash=false
file=/dev/null
usage="./doit [ --dump ] parseable-file"
exec="./parse_results_plot.py $@"
if [ $# -eq 0 ]
then
    echo >&2 "$usage"
    exit
fi

for arg
do
    case "$arg" in 
        --help|-h|--usage)
            if ! $found_ddash
            then
                echo >&2 "$usage"
                exit
            fi ;;
        --)
            found_ddash=true  ;;
        --dump)
            exec=cat ;;
        *)
            if $found_ddash
            then file="$arg"
                break 
            elif [ ${arg::1} != - ]
            then
                file="$arg"
            fi ;;
    esac
done            

./parserun.py $@ < "$file" > $TMPFILE
# Don't truncate for parse_results if exec is cat
if [ "$exec" != cat ]
then
    sed -i"" "1,2d" "$TMPFILE"
fi
if [ $? = 0 ] ; then $exec < $TMPFILE ; else false ; fi
